# Generated by Django 4.1.3 on 2022-12-16 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0003_newsstory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsstory',
            name='favourites',
            field=models.ManyToManyField(related_name='news_stories', to=settings.AUTH_USER_MODEL),
        ),
    ]
